### ISSUE TITLE
Lawsuit #314: Thea's SuperStrong Awesome PowerPick

### ISSUE THREAD

**Issue by Hallowizer** [lynaevm/BreakOut#10]
I am here to sue Thea's SuperStrong Awesome PowerPick Inc. The label on their PowerPick says "Guarenteed to break any block". This is false advertising, because I cannot break the Obsidian shell with it...

**Comment by lynaevm** [comment]
haha, good point.  I'll have my lawyers talk to your lawyers...

**Comment by Hallowizer** [comment]
...not like I'm trying to make your lawyers BreakIn to my prison so I get an easy escape...
