### ISSUE TITLE
can't complete sieving for freedom quest i have all the materials but it wont let me claim the reward what do i do? 

### ISSUE THREAD

**Issue by nukeassassin24** [lynaevm/BreakOut#11]
![2019-02-10_20 26 38](https://user-images.githubusercontent.com/47510960/52542876-49408e80-2d72-11e9-9a3d-5b4361c0bbfc.png)

**Comment by Hallowizer** [comment]
There's a second task. Click the right arrow to the right of Detect/Submit.

EDIT: It says "2 pages" for a reason.

**Comment by maniacisal** [comment]
OMG its not obvious at all
