### ISSUE TITLE
Unfair Fluix Rewards

### ISSUE THREAD

**Issue by Hallowizer** [lynaevm/BreakOut#12]
Hi! I find the rewards from the Fluix quest unfair, because it completely skips some major work. I removed the quest rewards from that quest locally, but is it possible that you make that change in the modpack itself? Thanks!

**Comment by lynaevm** [comment]
I included AE2 in this pack to give players new to modded a chance to learn some of the basic mechanics in a low-stress environment but it is, frankly, somewhat unnecessary.  I didn't want to make people invest a lot of time and effort into something gratuitous and add to the number of players that are anti-ae2 so I tried to make it fairly easy for people.  If you like it hard, you are welcome to do it the long way!

**Comment by Hallowizer** [comment]
Yup, I threw those rewards out lol
