### ISSUE TITLE
gearwork die

### ISSUE THREAD

**Issue by ODEAJA1234** [lynaevm/BreakOut#13]
MY GEARWORK DIE IS DISAPEAR PLZZZ HELP MEEEEEEEEEEEE HOW DARE U TO STEAL MY GEARWORK DIE !?!?!?!?!??!?!?!??!?!?!?!?!?!?!?!?

![2019-02-11_11 32 03](https://user-images.githubusercontent.com/47514015/52546341-ec37ed80-2df0-11e9-90e7-27ff64b9b2e5.png)

**Comment by Hallowizer** [comment]
If you open the GUI for the Compactor, and go to Augments, you can take it out.
