### ISSUE TITLE
Obtain infinite Dirt

### ISSUE THREAD

**Issue by SuperFurias** [lynaevm/BreakOut#14]
I do not think it's a bug because the crafting is vanilla, and also the way it works but through this thing it is possible to duplicate the dirt. I'll explain the bug
You must first have two pieces of dirt and two pieces of gravel, putting them in check in the crafting you will get 4 cubes of coarse dirt, you say .. and so? By placing these 4 cubes through a hoe it is possible to convert them into normal land. So after making the cobblestone generator and then endless cobblestone = infinite gravel, you can also get endless dirt with this little game
2 Dirt + 2 Gravel = 4 Coarse Dirt
4 Coarse Dirt + Hoe = 4 Dirt

**Comment by Hallowizer** [comment]
I used this too, and it might be a glitch. I know in SkyFactory, they made the Coarse Dirt recipe only yield 2 Coarse Dirt, so Dirt cannot be duplicated in this method.

**Comment by lynaevm** [comment]
This pack isn't necessarily meant to be hard, especially for clever people :) After all, another way to get dirt is to compost the string which you get for free.  thanks for reporting though!
