### ISSUE TITLE
Resource Renewability

### ISSUE THREAD

**Issue by Hallowizer** [lynaevm/BreakOut#16]
Hi! I created a thread 2 weeks ago, mentioning some suggestions about renewability. Before I continue, if you don't know what renewability is, you can read about it [here](https://minecraft.gamepedia.com/Renewable_resource). I have found a few more things about this, which I will list here.

# Sky Stone
Because Sky Stone is nonrenewable, I cannot create infinitely many ME Controllers. I also cannot create infinitely many Sticky Pistons, which means I cannot create infinitely many piston doors. Additionally, meteor themed things will be limited, because there is only so much Sky Stone.

# Bedrock
It is amazing that Bedrock can be created in this pack. However, this creation is not a renewable method. It would look very cool to have Bedrock everywhere, but there is only a single box of it. Maybe an Orb of Infinity can be ground down to 6 "Bedrock Dust", and each Bedrock Dust can be put in a barrel of Tectonic Petrotheum to make a Bedrock?

# Polished Blocks
My notes on the polished blocks are very similar, so I have grouped them together here.

## Polished Obsidian
Polished Obsidian is needed to create some machines, making them nonrenewable. This means I can only create so many block breakers in the world. It also means I can only build a limited amount of super hard structures, making this difficult.

### Polished Granite
The only reason I see for Polished Granite not being craftable is that it can be turned into Polished Obsidian. However, with what I mention below, this recipe can be removed, allowing Polished Granite to be craftable again.

## Polished Andensite/Diorite
I can see why you removed these recipes. You don't want the player to accidentally craft these and get a block in their way.

## Crafting
For Polished Obsidian, Polished Andensite, and Polished Diorite, I have an idea for an alternate recipe. Each of these materials can have a cutter, made from a Stick and one of the respective material. To polish a block, it can be crafted with its respective cutter, or a cutter of a higher tier. This will consume 1 durability. The tiers go from Andensite to Diorite, then finally Obsidian. If this cannot be achieved with ContentTweaker, let me know and I can try to write this in its own mod.

**Comment by lynaevm** [comment]
I simply do not see a very high demand for these blocks being infinitely available.
