### ISSUE TITLE
String quest, spelling (wood instead of wool).

### ISSUE THREAD

**Issue by hedstr0m** [lynaevm/BreakOut#17]
"Curious... When I try to grab the wood(!) with my bare hands, I come up with only fluff and string." 
I believe it should read: 
"Curious... When I try to grab the wool with my bare hands, I come up with only fluff and string." 

Just updated the pack to 1.9 and started a new world.

**Comment by Hallowizer** [comment]
I agree, I think it should say wool.

**Comment by lynaevm** [comment]
Thanks, fixed in most recent update.
