### ISSUE TITLE
Obsidian pickaxe is impossible to get?

### ISSUE THREAD

**Issue by Surawsome** [lynaevm/BreakOut#18]
The metal rods for the pickaxe require invar and you can't get the invar because you need gears, but to get those gears you have to make a machine that requires gears... see where I'm going? Also if you try to go through the allow smelter method you get in the same predicament because the alloy smelter you need iron alloy but you need an alloy smelter to make it. Please fix this because i can't progress

**Comment by Surawsome** [comment]
You also can't complete the quest even if you cheat in the pick ^

**Comment by Hallowizer** [comment]
You can use the Quartz Grindstone.
