### ISSUE TITLE
Can't get Iron Alloy Ingot

### ISSUE THREAD

**Issue by dracnis** [lynaevm/BreakOut#20]
We need the alloy smelter to craft the Iron Alloy Ingot but need 4 of them to craft the alloy smelter ...

**Comment by dracnis** [comment]
I just saw that there must be 4 item frames I didn't have, so normally we have enough to crack the first alloy smelter.

**Comment by Hallowizer** [comment]
All 4 crossroads have catch 22s like this, to keep you from starting the mods in the main room.
