### ISSUE TITLE
Cant complete grindstone challange

### ISSUE THREAD

**Issue by KillerKana** [lynaevm/BreakOut#21]
![Screenshot (249)](https://user-images.githubusercontent.com/48400350/54080957-65e5cd00-4304-11e9-8d60-d97bb129e498.png)
it seems to me that crushed diorite challange is missing

**Comment by lynaevm** [comment]
You are correct! this was fixed in update 1.97.  Sorry for the delay

**Comment by Hallowizer** [comment]
Can somebody close this issue?
