### ISSUE TITLE
Possible dupe bug

### ISSUE THREAD

**Issue by inkblot0** [lynaevm/BreakOut#3]
One can use use diamond nuggets from sifting gravel and ender dust to create 1 diamond from 8 nuggets and 1 dust, craft that into 9 nuggets to be ahead 1. Adding to that, with a 15% chance to reclaim glowstone from sieving crushed end stone, ender dust can be created almost infinitely.

**Comment by lynaevm** [comment]
Both of these work, but require effort in appropriate proportion to their return so I am not concerned.  Thank you.

**Comment by Hallowizer** [comment]
Ender Dust cannot be created almost infinitely, because there is only a 15% chance of reclaiming glowstone dust. For every 20 end stone you sift, you will only get 3 glowstone dust back, so this does not create a dupe bug.
