### ISSUE TITLE
Can't submit quest

### ISSUE THREAD

**Issue by joejoe1456** [lynaevm/BreakOut#37]
![2020-12-05_15 16 44](https://user-images.githubusercontent.com/75544883/101262464-f38a6280-370c-11eb-8300-9ca6709d1ee7.png)
I have both of the things needed to finish the quest, but nothing happens when I hit the submit button. The quest menu says I only have one of the two objects needed, but I clearly have everything needed. I have tried restarting the forge launcher and making the items again, but nothing is working.

**Comment by joejoe1456** [comment]
It

**Comment by joejoe1456** [comment]
It worked after I made 16 gravel, even though it never told me to?

**Comment by maniacisal** [comment]
I'm seeing this now. The issue is that there are two pages in the book. There is an arrow key next to "Detect/Submit" that shows the next page.
