### ISSUE TITLE
Iron Pickaxe Recipe

### ISSUE THREAD

**Issue by DeadpoolDE** [lynaevm/BreakOut#4]
The Recipe for the Iron Pickaxe uses some Sort of "Baguettes" (Food) instead of sticks. I am playing in Version 1.8 . In the "BreakOut" Letsplay from Ector Vynk he crafted the Iron Pickaxe with sticks. Don't know the Version he is using.

**Comment by lynaevm** [comment]
Ector Vynk was on an un-updated version of the pack at that time; the recipe has been changed as part of ongoing development.
