### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Hallowizer** [lynaevm/BreakOut#6]
This is a great pack, but a couple things are bugging me:

1. Sky Stone is nonrenewable! That means I cannot create infinite ME Systems, which bugs me, even though nobody needs to do that. The main problem with this is that since Sticky Pistons require Sky Stone, so they cannot be renewably created.
2. Bedrock is nonrenewable! Which means all of the Bedrock I get is the Bedrock around the outer shell.

Can you try to change these two things? Thanks!

**Comment by lynaevm** [comment]
Sieving skystone gives skystone dust, which can be used on lava to make more skystone.  So while it isn't infinitely renewable, it is recursive enough to give you as much skystone as one could reasonably need, especially if you use enchanted sieves.

What on earth would you do with more bedrock?

**Comment by Hallowizer** [comment]
What on Earth would I do with bedrock? I'm not on Earth!

If there was more bedrock, I would build a base out of bedrock once I broke out, because why not!
