### ISSUE TITLE
Ice block quest repeatable

### ISSUE THREAD

**Issue by 7vanessa77** [lynaevm/BreakOut#8]
I keep on blocking my water source and there is no other way (apart from the oak crucible) to get water, however, I do not have leaves. Is there some way you can make the ice block quest repeatable, so I do not accidentally block my water source.

**Comment by Hallowizer** [comment]
There is a way besides the oak crucible to get water. If you have your water source, you can bottle it with a glass bottle, then put the bottle into a barrel. Repeat 3 more times and you have a full barrel, without consuming any water. You can keep a backup water bucket in your chest this way.

**Comment by lynaevm** [comment]
I added the ice box quest to give players a second chance if they did what you did and accidentally destroyed their waterblock.  If they repeat the mistake... well, you're only a few minutes into the game at that point and can restart using the commands found in "/island".
